apiVersion: v1
kind: PersistentVolume
metadata:
  name: ankesh-pv
  namespace: demo
  labels:
    type: ankesh-pv
spec:
  claimRef:
    name: ankesh-pvc
    namespace: demo
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/redis