apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ankesh-pvc
  namespace: demo
  labels:
      type: ankesh-pvc
spec:
  volumeName: ankesh-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi