apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-ss
  namespace: demo
spec:
  serviceName: "redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2.0-alpine
        ports:
        - containerPort: 6379
          name: redis-ss
        command:
          - redis-server
          - "/etc/redis-config.conf"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-claim
          mountPath: /etc
        - name: redis-dir
          mountPath: /var/lib/redis
        resources:
          limits:
            cpu: "200m"
            memory: 200mi
      volumes:
      - name: config-map
        configMap:
          name: redis-ss-configuration                  
  volumeClaimTemplates:
  - metadata:
      name: redis-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: redis-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
#   namespace : demo
#   labels:
#     app: redis
# spec:
#   type: ClusterIP
#   ports:
#   - port: 6379
#     name: redis-server
#   clusterIP: None
#   selector:
#     app: redis
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: redis-server
#   namespace: demo
# spec:
#   serviceName: "redis"
#   replicas: 2
#   selector:
#     matchLabels:
#       app: redis
#   template:
#     metadata:
#       labels:
#         app: redis
#     spec:
#       containers:
#       - name: redis
#         image: redis:7.2.0-alpine
#         ports:
#         - containerPort: 6379
#           name: redis-server
#         resources:
#           limits:
#             cpu: "200m"
#             memory: 200mi
#         volumeMounts:
#         - name: redis-data
#           mountPath: /var/lib/redis
#       volumes:
#         - name: config-map
#           configMap:
#             name: redis-server
#   volumeClaimTemplates:
#     - metadata:
#         name: redis-data
#       spec:
#         accessModes: [ "ReadWriteOnce" ]
#         resources:
#           requests:
#             storage: 1Gi