apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: demo
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  clusterIP: None
  selector:
    app: redis

# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
#   namespace : demo
#   labels:
#     app: redis
# spec:
#   type: ClusterIP
#   ports:
#   - port: 6379
#     name: redis-server
#   clusterIP: None
#   selector:
#     app: redis